require "#{Rails.root}/db/seed_helper.rb"

seed_timer("Clearing phoneme table... ") {
  Phoneme.delete_all
}
seed_timer("Populating phoneme table... ") {
  Phoneme.create!([{:name => "aa", :stress => 0, :ptype => "vowel"},
                   {:name => "aa", :stress => 1, :ptype => "vowel"},
                   {:name => "aa", :stress => 2, :ptype => "vowel"},
                   {:name => "ae", :stress => 0, :ptype => "vowel"},
                   {:name => "ae", :stress => 1, :ptype => "vowel"},
                   {:name => "ae", :stress => 2, :ptype => "vowel"},
                   {:name => "ah", :stress => 0, :ptype => "vowel"},
                   {:name => "ah", :stress => 1, :ptype => "vowel"},
                   {:name => "ah", :stress => 2, :ptype => "vowel"},
                   {:name => "ao", :stress => 0, :ptype => "vowel"},
                   {:name => "ao", :stress => 1, :ptype => "vowel"},
                   {:name => "ao", :stress => 2, :ptype => "vowel"},
                   {:name => "aw", :stress => 0, :ptype => "vowel"},
                   {:name => "aw", :stress => 1, :ptype => "vowel"},
                   {:name => "aw", :stress => 2, :ptype => "vowel"},
                   {:name => "ay", :stress => 0, :ptype => "vowel"},
                   {:name => "ay", :stress => 1, :ptype => "vowel"},
                   {:name => "ay", :stress => 2, :ptype => "vowel"},
                   {:name => "b",  :stress => 0, :ptype => "stop"},
                   {:name => "ch", :stress => 0, :ptype => "affricate"},
                   {:name => "d",  :stress => 0, :ptype => "stop"},
                   {:name => "dh", :stress => 0, :ptype => "fricative"},
                   {:name => "eh", :stress => 0, :ptype => "vowel"},
                   {:name => "eh", :stress => 1, :ptype => "vowel"},
                   {:name => "eh", :stress => 2, :ptype => "vowel"},
                   {:name => "er", :stress => 0, :ptype => "vowel"},
                   {:name => "er", :stress => 1, :ptype => "vowel"},
                   {:name => "er", :stress => 2, :ptype => "vowel"},
                   {:name => "ey", :stress => 0, :ptype => "vowel"},
                   {:name => "ey", :stress => 1, :ptype => "vowel"},
                   {:name => "ey", :stress => 2, :ptype => "vowel"},
                   {:name => "f",  :stress => 0, :ptype => "fricative"},
                   {:name => "g",  :stress => 0, :ptype => "stop"},
                   {:name => "hh", :stress => 0, :ptype => "aspirate"},
                   {:name => "ih", :stress => 0, :ptype => "vowel"},
                   {:name => "ih", :stress => 1, :ptype => "vowel"},
                   {:name => "ih", :stress => 2, :ptype => "vowel"},
                   {:name => "iy", :stress => 0, :ptype => "vowel"},
                   {:name => "iy", :stress => 1, :ptype => "vowel"},
                   {:name => "iy", :stress => 2, :ptype => "vowel"},
                   {:name => "jh", :stress => 0, :ptype => "affricate"},
                   {:name => "k",  :stress => 0, :ptype => "stop"},
                   {:name => "l",  :stress => 0, :ptype => "liquid"},
                   {:name => "m",  :stress => 0, :ptype => "nasal"},
                   {:name => "n",  :stress => 0, :ptype => "nasal"},
                   {:name => "ng", :stress => 0, :ptype => "nasal"},
                   {:name => "ow", :stress => 0, :ptype => "vowel"},
                   {:name => "ow", :stress => 1, :ptype => "vowel"},
                   {:name => "ow", :stress => 2, :ptype => "vowel"},
                   {:name => "oy", :stress => 0, :ptype => "vowel"},
                   {:name => "oy", :stress => 1, :ptype => "vowel"},
                   {:name => "oy", :stress => 2, :ptype => "vowel"},
                   {:name => "p",  :stress => 0, :ptype => "stop"},
                   {:name => "r",  :stress => 0, :ptype => "liquid"},
                   {:name => "s",  :stress => 0, :ptype => "fricative"},
                   {:name => "sh", :stress => 0, :ptype => "fricative"},
                   {:name => "t",  :stress => 0, :ptype => "stop"},
                   {:name => "th", :stress => 0, :ptype => "fricative"},
                   {:name => "uh", :stress => 0, :ptype => "vowel"},
                   {:name => "uh", :stress => 1, :ptype => "vowel"},
                   {:name => "uh", :stress => 2, :ptype => "vowel"},
                   {:name => "uw", :stress => 0, :ptype => "vowel"},
                   {:name => "uw", :stress => 1, :ptype => "vowel"},
                   {:name => "uw", :stress => 2, :ptype => "vowel"},
                   {:name => "v",  :stress => 0, :ptype => "fricative"},
                   {:name => "w",  :stress => 0, :ptype => "semivowel"},
                   {:name => "y",  :stress => 0, :ptype => "semivowel"},
                   {:name => "z",  :stress => 0, :ptype => "fricative"},
                   {:name => "zh", :stress => 0, :ptype => "fricative"}])
}